
-- DATA PREPARATION AND UNDERSTANDING

-- 1. What is the total number of rows in each of the 3 tables in the database?

Select Count(customer_Id) as Total_Rows
from Customer
Union
Select Count(prod_cat_code)
from prod_cat_info
Union
Select Count(transaction_id)
from transactions


-- 2. What is the total number of transactions that have a return? 

Select Count(transaction_id) as [Total no. of returns]
From Transactions
Where Qty < 0

-- 3. As you would have noticed, the dates provided across the datasets are not in a 
-- correct format. As first steps, pls convert the date variables into valid date formats 
-- before proceeding ahead.

Select customer_Id, Cast(DOB  as date) as DOB, Gender, city_code
From Customer


Select transaction_Id, cust_id, Cast(tran_date  as date) as tran_date, 
	   prod_subcat_code, prod_cat_code, Qty, Rate, Tax, total_amt, Store_type
	   From transactions


-- 4. What is the time range of the transaction data available for analysis? Show the 
-- output in number of days, months and years simultaneously in different columns.

Select datediff(DAY, Min(tran_date), Max(tran_date)) as Day_diff, 
	   datediff(MONTH, Min(tran_date), Max(tran_date)) as Month_diff,
	   datediff(YEAR, Min(tran_date), Max(tran_date)) as Year_diff
	   From transactions


-- 5. Which product category does the sub-category “DIY” belong to? 

Select prod_cat
From prod_cat_info
Where prod_subcat = 'DIY'



--DATA ANALYSIS 

-- 1. Which channel is most frequently used for transactions? 

Select Top 1 Store_type, Count(transaction_id) as [No. of transactions]
From Transactions
Group by Store_type
Order by [No. of transactions] Desc

-- 2. What is the count of Male and Female customers in the database? 

Select Gender, Count(customer_Id) as [No. of Customers]
From Customer
Where Gender <> ' '
Group by Gender


-- 3. From which city do we have the maximum number of customers and how many? 

Select Top 1 city_code, Count(customer_Id) as [No. of Customers]
From Customer
Group by city_code
Order by [No. of Customers] Desc

-- 4. How many sub-categories are there under the Books category? 

Select prod_cat, Count(prod_cat_code) as [No. of sub-categories]
From prod_cat_info
Where prod_cat = 'Books'
Group by prod_cat

-- 5. What is the maximum quantity of products ever ordered? 

Select  Top 1 tran_date, Sum(Qty) as Total_Quantity
From Transactions
Group by tran_date
Order by Total_Quantity Desc


-- 6. What is the net total revenue generated in categories Electronics and Books? 

Select prod_cat, Sum(total_amt) as Total_revenue
From Transactions as T
Inner Join prod_cat_info as P
ON T.prod_cat_code = P.prod_cat_code
             AND
T.prod_subcat_code = P.prod_sub_cat_code
Where prod_cat IN ('Electronics', 'Books')
Group by prod_cat


-- 7. How many customers have >10 transactions with us, excluding returns? 

Select cust_id, Count(transaction_id) as [No. of Transactions]
From Transactions
Where total_amt > 0
Group by cust_id
Having Count(transaction_id) > 10

-- 8. What is the combined revenue earned from the “Electronics” & “Clothing” 
-- categories, from “Flagship stores”?

Select Store_type, Sum(total_amt) as Total_revenue
From Transactions as T
Inner Join prod_cat_info as P
ON T.prod_cat_code = P.prod_cat_code
            AND
T.prod_subcat_code = P.prod_sub_cat_code
Where prod_cat IN ('Electronics', 'Clothing')
              AND
Store_type = 'Flagship Store'
Group by Store_type

-- 9. What is the total revenue generated from “Male” customers in “Electronics” 
-- category? Output should display total revenue by prod sub-cat.

Select prod_subcat, Sum(total_amt) as Total_revenue 
From Customer as C
Inner Join Transactions as T
ON C.customer_Id = T.cust_id
Inner Join prod_cat_info as P
ON T.prod_cat_code = P.prod_cat_code
             AND
T.prod_subcat_code = P.prod_sub_cat_code
Where Gender = 'M'
     AND
prod_cat = 'Electronics'
Group by prod_subcat

-- 10.What is percentage of sales and returns by product sub category; display only top 
-- 5 sub categories in terms of sales?

Select  Top 5 prod_subcat_code, 
Sum(Case
When total_amt > 0
then total_amt
Else 0
End) as Sales,
Sum(Case
When total_amt < 0
then Abs(total_amt)
Else 0
End) as [Returns]
From Transactions
Group by prod_subcat_code
Order by Sales Desc

-- 11. For all customers aged between 25 to 35 years find what is the net total revenue 
-- generated by these consumers in last 30 days of transactions from max transaction 
-- date available in the data?


Select Sum(Total_amt) as Total_revenue
from (
Select cust_id, Total_amt, 
DATEDIFF(Year, DOB, getdate()) as Age
From Customer as C
Inner Join Transactions as T
on C.customer_Id = T.cust_id
Where DATEDIFF(Year, DOB, getdate()) Between 25 AND 35
					AND 
DATEDIFF(Day, tran_date, (Select Max(tran_date) From Transactions)) < 30
) as X

-- 12.Which product category has seen the max value of returns in the last 3 months of 
-- transactions? 

Select Top 1 prod_cat_code, Abs(Sum(Total_amt)) as Total_Returns
From Transactions
Where total_amt < 0
      AND
DATEDIFF(Month, tran_date, (Select Max(tran_date) From Transactions)) < 3
Group by prod_cat_code
Order by Total_Returns Desc

-- 13.Which store-type sells the maximum products; by value of sales amount and by 
-- quantity sold?

Select Top 1 Store_type, Sum(Total_amt) as Total_Sales, Sum(Qty) as Total_quantity
From Transactions
Group by Store_type
Order by Total_Sales Desc, Total_quantity Desc

-- 14.What are the categories for which average revenue is above the overall average. 

Select prod_cat_code, Avg(Total_amt) as Average_revenue
From Transactions
Group by prod_cat_code
Having Avg(Total_amt) > (Select Avg(Total_Amt) From Transactions)

-- 15. Find the average and total revenue by each subcategory for the categories which 
-- are among top 5 categories in terms of quantity sold.

Select prod_cat_code, prod_subcat_code, Sum(Total_amt) as Total_revenue, 
Avg(Total_amt) as Average_revenue
From Transactions
Where prod_cat_code IN
(
Select Top 5 prod_cat_code
From Transactions
Group by prod_cat_code
Order by Sum(Qty)
)
Group by prod_cat_code, prod_subcat_code
Order by prod_cat_code Asc, prod_subcat_code Asc
